### ISSUE TITLE
Manifest generation and integration

### ISSUE THREAD

**Issue by varl** [dhis2/cli#10]
https://github.com/dhis2/d2-manifest is something we should think about when we do the `create-app` scripts. It will be necessary for the appstore.

Coupled with this logic in [core which replaces `*` with the server url](https://github.com/dhis2/dhis2-core/blob/4645590a8c3faec8d4f22a3245505b986e8e335f/dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java#L193) we have a mechanism for an app to discover the server base url if it loads the `manifest.webapp` file through a request.

**Comment by amcgee** [comment]
I agree this functionality should be contained within the `cli` and `d2-app-scripts`, but I'm wary of this server-injected URL approach.  It's definitely a step up from requiring a statically-defined relative URL but I do think we could rethink how to server discovery works.

**Comment by varl** [comment]
Agreed on figuring out a better mechanism for the server discovery.

The point about the "*" mechanism is more that we have, and have had, this mechanism for a long time, so we definitely should be using that _already_ over hard-coding in an assumption about where the API is located. That note might be misplaced in this issue however.

**Comment by amcgee** [comment]
Nice, definitely +100 to using what's already there and not hard-coding things!
