### ISSUE TITLE
broken link for @dhis2/cli-app-scripts

### ISSUE THREAD

**Issue by aucampia** [dhis2/cli#151]
Link in the the [README](https://github.com/dhis2/cli/blob/master/README.md) for `@dhis2/cli-app-scripts` points to https://github.com/dhis2/app-platform/cli which does not exist. I'm guessing it should point to https://github.com/dhis2/app-platform

**Comment by amcgee** [comment]
Hi @aucampia - thanks for noticing the broken link, it should actually point to https://github.com/dhis2/app-platform/tree/master/cli (the source for the `cli-app-scripts` module)

I've fixed this now.  In the future feel free to make edits like these (or even more complicated ones) yourself and open a pull request!
