### ISSUE TITLE
Period in cluster name causes wrong runtime environment

### ISSUE THREAD

**Issue by varl** [dhis2/cli#169]
When I have a period in the cluster name (e.g. `d2 cluster up 2.31`) I get unexpected behaviour when spinning up that cluster. 

## Given the configuration

`~/.config/d2/config.js`:
```js
module.exports = {
    cluster: {
        channel: 'stable',
        clusters: {
            '2.31': {
                channel: 'dev',
                dbVersion: '2.31',
                dhis2Version: '2.31',
                customContext: true,
                port: 8231
            },
        },
    },
}
```

Note that the `channel` is set to "dev" in the config. When running:

```
d2 cluster up 2.31 --seed --update --verbose
```

I get the following results:

## Actual runtime env:

```
[DEBUG] Runtime environment
 { DHIS2_CORE_NAME: '2.31',
  DHIS2_CORE_IMAGE: 'dhis2/core:2.31',
  DHIS2_CORE_CONTEXT_PATH: '/2.31',
  DHIS2_CORE_VERSION: '2.31',
  DHIS2_CORE_DB_VERSION: '2.31',
  DHIS2_CORE_PORT: 8231 }
```

It tries to use a stable core image, when it should have evaluated to core-dev.

## Expected runtime env

```
[DEBUG] Runtime environment
 { DHIS2_CORE_NAME: '2.31',
  DHIS2_CORE_IMAGE: 'dhis2/core-dev:2.31',
  DHIS2_CORE_CONTEXT_PATH: '/2.31',
  DHIS2_CORE_VERSION: '2.31',
  DHIS2_CORE_DB_VERSION: '2.31',
  DHIS2_CORE_PORT: 8231 }
```

I think it is related to the period in "2.31", as replacing the config with "231" works as intended.

**Comment by amcgee** [comment]
@varl I haven't been able to reproduce this... I've used names with periods many times, and stopping/restarting one with the exact configuration you have still uses the `core-dev` image...  any other thoughts on what might be going on?

**Comment by amcgee** [comment]
I'm actually having trouble getting any cluster configs from `.config/d2/config.js` to load.... do you have a `config.json` file in your `.cache/d2/clusters/2.31` directory?  That will probably take preference.

**Comment by varl** [comment]
I'll do some more debugging, maybe a lingering cache is the problem, it's been a month already and I don't recall the fine details.

I ran into this setting it up on a clean system (fresh debian install) so I think the cache should have been empty.

**Comment by amcgee** [comment]
I think this was a cache issue, closing
