### ISSUE TITLE
Initializing a new cluster with a database seed creates a malfunctioning instance

### ISSUE THREAD

**Issue by awgaan** [dhis2/cli#181]
When I try to create a new cluster using the `Sierra Leone` test database as a seed I end up with an instance that doesn't respond to HTP requests and that for some reason redirects all requests to the DHIS2 dashboard.

# Timeline
Ran
```
d2 cluster up sierra --db-version 2.32 --dhis2-version 2.32.0 --seed 
```
Tried to open `localhost:8080`. Doesn't respond at all. Times out.
```
$ docker ps
COMMAND                  CREATED             STATUS              PORTS                  NAMES
"catalina.sh run"        32 minutes ago      Up 32 minutes       8080/tcp               d2-cluster-sierra_core_1
"/app/docker-entrypo…"   32 minutes ago      Up 32 minutes       0.0.0.0:8080->80/tcp   d2-cluster-sierra_gateway_1
"docker-entrypoint.s…"   2 months ago        Up 32 minutes       5432/tcp               d2-cluster-sierra_db_1
```
Waited 30 minutes just to make sure I didn't stop any remaining database queries.
Stopped the instance and restarted
```
$ d2 c down sierra
$ d2 c up sierra
----
$ tail $(d2 c logs sierra)
 core_1     | 31-Oct-2019 20:20:24.949 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 115099 ms
```
Going to `localhost:8080` redirects to `localhost:8080/dhis-web-dashboard`.

# Maybe relevant
On the first cluster boot, openssl dhparam generation takes several minutes to complete and uses 100% CPU (1 core).

# System info
```
$ d2 debug system
  System:
    OS: Linux 5.3 Arch Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 1022.19 MB / 7.66 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.16.1 - ~/.nvm/versions/node/v8.16.1/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.1/bin/npm
  Utilities:
    Git: 2.23.0 - /usr/bin/git
  Virtualization:
    Docker: 19.03.4 - /usr/bin/docker
  IDEs:
    Sublime Text: Not Found
    VSCode: Not Found
  Databases:
    PostgreSQL: Not Found

$ d2 --version
2.6.0
 ```

# Other
Tried this on my own machine several times and on another master student's machine (mac) as well. Same type of unexpected behavior.

**Comment by amcgee** [comment]
Hi @awgaan - does this happen with the latest version of `2.32`, `2.32.2`?  It may be an issue that was resolved in the patch release.

Also, you should run `d2 cluster down sierra --clean` to make sure it removes all the containers and data, it looks like some things are stale in your environment (one of the containers was created 2 months ago)

**Comment by amcgee** [comment]
Hi @awgaan - is this still happening for you?  Did you try the above recommendations?

**Comment by awgaan** [comment]
Sorry, I haven't found time to try any of the above recommendations yet.
My final exam is on Thursday, so I'll try to get it done after that.

**Comment by amcgee** [comment]
No worries, just let me know if you see this again.  Good luck with the exam!

**Comment by awgaan** [comment]
That one old database container was the problem I think. Just tested with `db-version: 2.33` and `dhis2-version: 2.33.0` and that worked fine.

I think the spin up command should wait a couple of seconds before attempting to connect to the newly created database. Because right now it can't connect to the PostgreSQL server and I have to re-run the initialization command one more time in order to get the database seeded and get the core and gateway started.

```
# first run
$ d2 cluster up b --db-version 2.33 --dhis2-version 2.33.0 --seed 
Initializing Docker Compose repository... 
Found cached database version 2.33, use --update to re-download 
Restoring database (this may take some time)... 
Creating network "d2-cluster-b_default" with the default driver
 Creating volume "d2-cluster-b_datadb" with default driver
 Creating volume "d2-cluster-b_home" with default driver
Creating d2-cluster-b_db_1 ... done
 psql: could not connect to server: Connection refused
	Is the server running on host "db" (172.22.0.2) and accepting
	TCP/IP connections on port 5432?
 read unix @->/run/docker.sock: read: connection reset by peer
```
