### ISSUE TITLE
d2-cluster enhancements

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli#21]
Follow-on enhancements from #17:

- [x] Wait for tomcat to start, restart gateway server (thanks @ismay for amcgee/dhis2-backend#1)
- [ ] use real verbs for commands up, down, logs? (BREAKING CHANGE)
- [ ] Pass cluster version before verb? (BREAKING CHANGE)
- [ ] Once core has started up (or failed to start!) notify the user of error or availability at URL

**Comment by ismay** [comment]
This would help with point 1: https://github.com/amcgee/dhis2-backend/pull/1

**Comment by amcgee** [comment]
Thanks for pinging that PR @ismay, I hadn't seen it!  It's merged now, so item (1) above is mostly fixed.  It would still be nice to notify the user when the server is actually available, but I'll make that a separate item.

To pull down the latest `docker-compose` configuration and take advantage of this enhancement, use `d2 cluster up --force` (this will invalidate the local cache and download a new copy of amcgee/dhis2-backend)

**Comment by varl** [comment]
>Pass cluster version before verb? (BREAKING CHANGE)

This might be in conflict with what #45 wants to do.

**Comment by amcgee** [comment]
@varl I think they're compatible, because you still want to be able to interact with a single-version cluster even if they're all exposed on a single port.  For instance, I might want to get the logs for my `2.32test` cluster.  I'd like to be able to do anything to that cluster from the `d2 cluster 2.32test` namespace rather than passing `2.32test` as an argument to various commands, I think?  I don't think it's crucial, but I do find it a little more intuitive than `d2 cluster logs 2.32test`

**Comment by varl** [comment]
I do tend to do multiple operations on the same cluster so I can get behind that.
