### ISSUE TITLE
`d2 cluster up` should support an interactive mode

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli#282]
This should probably use the [inquirer](https://www.npmjs.com/package/inquirer) package which we use elsewhere for CLI prompts.

It would ideally fetch the available `channel`, `dhis2-version`, and `db-version` options from https://hub.docker.com/u/dhis2 and https://github.com/dhis2/dhis2-demo-db (and possibly support additional cluster types from https://github.com/dhis2/docker-compose).  I imagine the flow going something like this for a fresh `up`:

- What would you like to name this cluster? - `<generated-random-name>` (default) or any
- Which release channel do you want to use?  - `stable` (default), `dev`, `canary`, or `custom` (to support custom local images?)
  - (if `custom`) Which DHIS2 Core image would you like to use? - (list populated from images and tags in local `docker` service?)
  - (if not `custom`) Which DHIS2 version should be used for the Core image? - `latest` (default), `2.32`, `2.33.1` (etc, populated from Docker Hub based on the Channel selected)
- Would you like to seed the database? - `yes` (default) / `no`
  - (if `yes`) Which database version would you like to use? - `latest`, `2.32`, `2.33.1` (etc, populated from Docker Hub and with the default dynamically selected based on the core image version)

Some of these things could be cached to prevent synchronous HTTP requests, but that might not be necessary.  We'd also have to think about how this could be used for *modifying an existing cluster*, rather than spinning up a new one.

This could possibly be extended, through the use of cached API responses, to bash/zsh command-line auto-completion scripts.

**Comment by varl** [comment]
To modify an existing cluster we could populate the "default" option with whatever is in the cached config file, e.g.: `~/.cache/d2/cache/clusters/dev/config.json`:

```
{
    "channel": "dev",
    "dbVersion": "dev",
    "dhis2Version": "master",
    "customContext": false,
    "image": "dhis2/core{channel}:{version}",
    "port": 8080
}
```

And overwrite it which whatever the user wants.
