### ISSUE TITLE
`d2 cluster up` should check for compatible/installed version of docker-compose

### ISSUE THREAD

**Issue by erikarenhill** [dhis2/cli#289]
using an old version of docker-compose such as 1.17 from the ubuntu repository can cause some headache, maybe we should implement some minimum requirement version check when installing the cli tools, or trying to use the cluster features. Also not having docker-compose at all makes the shell scripts crash instead of outputting a user-friendly message.

**Comment by amcgee** [comment]
Closing as dup of #80

Minimum versions of docker and docker-compose are 18.06.0 and 1.22.0,
