### ISSUE TITLE
Sample database URLs need to be updated

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli#317]
The repository https://github.com/dhis2/dhis2-demo-db (which we currently use) has been frozen, so updates to demo DBs will no longer be available.  The canonical location for database images is now https://databases.dhis2.org, which is managed through AWX.  We need to update the configuration of `d2 cluster` to support database image discovery and retrieval from the new location.

**Comment by varl** [comment]
Since the source of truth for DB dumps is now S3, we may be able to use the Node bindings for S3 to get a list of the database dumps and download the correct one.
