### ISSUE TITLE
Line causing that d2 cluster up xxx --seed fails on Windows

### ISSUE THREAD

**Issue by dayures** [dhis2/cli#342]
This line is causing that the d2 create cluster xxx --seed fail on my windows 10, due to an issue of the path.

https://github.com/dhis2/cli/blob/c39f42ca1db369e9a3642f12327cdbb54d28a600/packages/cluster/src/helpers/db/restore.js#L38

using `scripts\\seed.sh` solves this issue

**Comment by varl** [comment]
Hi @dayures, thank you for the report.

This issue has been moved to JIRA: https://jira.dhis2.org/browse/CLI-7
